version: "3"
services:
  docker-manager:
    build: .
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUME_PATH}:/app/credentials.json:ro
    ports:
      - 8000:8000
    networks:
      - gamebattle

networks:
  gamebattle:
    driver: bridge
    name: gamebattle
