version: "3"
services:
  docker-manager:
    image: "rizerphe/gamebattle-docker-manager:latest"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUME_PATH:-/credentials.json}:/app/credentials.json:ro
    ports:
      - 5000:8000
    networks:
      - gamebattle

networks:
  gamebattle:
    driver: bridge
    name: gamebattle
