version: "3"
services:
  docker-manager:
    image: "rizerphe/gamebattle-docker-manager:latest"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CREDENTIALS_PATH:-/credentials.json}:/app/credentials.json:ro
      - ${GAMES_PATH:-/gamebattle}:/app/gamebattle
    ports:
      - 5000:8000
    networks:
      - gamebattle

networks:
  gamebattle:
    driver: bridge
    name: gamebattle
