version: "3"
services:
  docker-manager:
    image: "rizerphe/gamebattle-docker-manager:latest"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CREDENTIALS_PATH:-/credentials.json}:/app/credentials.json:ro
      - ${GAMES_PATH:-/gamebattle}:/app/gamebattle
      - /tmp:/tmp # TODO: find a better way to handle this
    ports:
      - 5000:8000
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      ENABLE_COMPETITION: ${ENABLE_COMPETITION}
      REPORT_WEBHOOK: ${REPORT_WEBHOOK}
      ADMIN_EMAILS: ${ADMIN_EMAILS}
    restart: always
  redis:
    image: redis:alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data
    restart: always

volumes:
  redis:
    driver: local
